PROTOCOLS = {'Total Knee Arthroplasty': {'body_region': 'Knee',
                             'type': 'Arthroplasty',
                             'frequency': '2-3x/week',
                             'duration': '12-24 weeks',
                             'outcome_measures': ['LEFS', 'KOOS', 'TUG'],
                             'red_flags': ['Fever',
                                           'Calf pain',
                                           'Excessive drainage',
                                           'Uncontrolled pain',
                                           'DVT signs'],
                             'precautions': ['Avoid twisting/pivoting early',
                                             'Avoid pillow under knee',
                                             'Monitor swelling'],
                             'weeks': {'0-1': ['Pain/edema control',
                                               'Heel slides',
                                               'Heel prop extension',
                                               'Quad sets',
                                               'SLR if no lag',
                                               'Gait training'],
                                       '1-4': ['Restore full extension',
                                               'Flexion >90°',
                                               'Bike for ROM',
                                               'SAQ',
                                               'Sit-to-stands',
                                               'Mini squats',
                                               'Balance'],
                                       '4-8': ['Flexion >110°',
                                               'Normalize gait',
                                               'Step-ups/downs',
                                               'Leg press',
                                               'Lunges',
                                               'SLS'],
                                       '8-12': ['Strength ≥80%',
                                                'Advanced strengthening',
                                                'Monster walks',
                                                'Uneven surface gait',
                                                'Aquatics if healed'],
                                       '12-24': ['Low-impact recreation',
                                                 'Higher-level strengthening',
                                                 'Return to activity with clearance']}},
 'Meniscus Repair': {'body_region': 'Knee',
                     'type': 'Arthroscopy',
                     'frequency': '2-3x/week',
                     'duration': '12-16+ weeks',
                     'outcome_measures': ['LEFS', 'KOOS'],
                     'red_flags': ['Increased swelling', 'Locking', 'DVT signs'],
                     'precautions': ['TDWB initially', 'Brace locked in extension', 'ROM limited to 90° early'],
                     'weeks': {'0-4': ['TDWB with crutches',
                                       'Brace locked extension',
                                       'ROM 0-90°',
                                       'Heel slides',
                                       'Quad sets',
                                       'SLR',
                                       'Patellar mobs'],
                               '4-6': ['Continue TDWB',
                                       'Open brace to 90°',
                                       'Advance ROM',
                                       'Light open-chain strengthening'],
                               '6-12': ['FWB',
                                        'Discontinue brace with quad control',
                                        'Bike',
                                        'Wall sits',
                                        'Lunges',
                                        'Balance'],
                               '12-16': ['Leg press',
                                         'Hamstring curls',
                                         'Advanced strengthening',
                                         'Proprioception',
                                         'Plyometrics']}},
 'Partial Meniscectomy': {'body_region': 'Knee',
                          'type': 'Arthroscopy',
                          'frequency': '2-3x/week',
                          'duration': '4-6 weeks',
                          'outcome_measures': ['LEFS', 'KOOS'],
                          'red_flags': ['Persistent swelling', 'Locking', 'DVT signs'],
                          'precautions': ['Progress as tolerated', 'Monitor swelling/pain'],
                          'weeks': {'0-2': ['WBAT',
                                            'Crutches 24-48 hrs PRN',
                                            'Full extension',
                                            'Heel slides',
                                            'Quad sets',
                                            'SLR',
                                            'Patellar mobs'],
                                    '2-4': ['Full ROM', 'Stationary bike', 'Wall sits', 'Lunges', 'Balance'],
                                    '4-6': ['Leg press',
                                            'Hamstring curls',
                                            'Advanced strengthening',
                                            'Plyometrics',
                                            'Proprioception']}},
 'Rotator Cuff Tendinopathy': {'body_region': 'Shoulder',
                               'type': 'Non-operative',
                               'frequency': '1-2x/week',
                               'duration': '4-8 weeks',
                               'outcome_measures': ['QuickDASH', 'SPADI'],
                               'red_flags': ['Progressive weakness', 'Traumatic loss of AROM'],
                               'precautions': ['Avoid painful overhead loading', 'No strengthening through sharp pain'],
                               'weeks': {'0-2': ['Pendulums',
                                                 'Cross-body stretch',
                                                 'Sleeper stretch',
                                                 'Passive IR/ER stretch'],
                                         '2-4': ['Rows',
                                                 'Band ER',
                                                 'Band IR',
                                                 'ER at 90° abduction',
                                                 'Scapular stabilization'],
                                         '4-6': ['Biceps curls',
                                                 'Triceps extensions',
                                                 'Trap strengthening',
                                                 'Scapular retraction/protraction'],
                                         '6+': ['Side-lying ER',
                                                'Side-lying IR',
                                                'Bent-over horizontal abduction',
                                                'Return to work/sport']}},
 'SLAP Repair': {'body_region': 'Shoulder',
                 'type': 'Labral Repair',
                 'frequency': '2-3x/week',
                 'duration': '16-24 weeks',
                 'outcome_measures': ['QuickDASH', 'SPADI'],
                 'red_flags': ['Instability', 'Increasing pain', 'Infection signs'],
                 'precautions': ['Sling early', 'Limit ER to 40° early', 'Avoid resisted biceps early'],
                 'weeks': {'0-4': ['Sling',
                                   'ER limit 40°',
                                   'Flexion to 140°',
                                   'Elbow/wrist ROM',
                                   'Grip',
                                   'Isometric ER/IR/ABD'],
                           '4-6': ['Discontinue sling', 'Increase ROM', 'Begin Theraband', 'Scapular stabilization'],
                           '6-12': ['Full AROM', 'Light weights', 'Advance bands', 'UBE'],
                           '12-24': ['Functional strengthening', 'Plyometrics', 'Sport/work-specific training']}},
 'Biceps Tenodesis': {'body_region': 'Shoulder',
                      'type': 'Tendon Procedure',
                      'frequency': '2-3x/week',
                      'duration': '12-16+ weeks',
                      'outcome_measures': ['QuickDASH', 'SPADI'],
                      'red_flags': ['Popeye deformity', 'Increasing pain', 'Infection signs'],
                      'precautions': ['No active elbow ROM early', 'No resisted biceps early', 'No lifting early'],
                      'weeks': {'0-3': ['Sling',
                                        'Pendulums',
                                        'PROM shoulder/elbow',
                                        'Scapular clocks',
                                        'No active elbow ROM',
                                        'No lifting'],
                                '3-6': ['AAROM/AROM',
                                        'Active elbow ROM no resistance',
                                        'Scar mob',
                                        'Sleeper/cross-body stretch'],
                                '6-8': ['Rhythmic stabilization',
                                        'Scaption',
                                        'ER/IR strengthening',
                                        'Push-up plus',
                                        'Prone rows'],
                                '8-16': ['Overhead strengthening', 'Progressive isotonics', 'Sport/work progression']}},
 'Total Shoulder Arthroplasty': {'body_region': 'Shoulder',
                                 'type': 'Arthroplasty',
                                 'frequency': '2-3x/week',
                                 'duration': '12-24 weeks',
                                 'outcome_measures': ['QuickDASH', 'SPADI'],
                                 'red_flags': ['Dislocation signs', 'Infection', 'Sudden loss of function'],
                                 'precautions': ['No shoulder AROM early',
                                                 'No lifting',
                                                 'Avoid excessive ER/extension early'],
                                 'weeks': {'0-4': ['Sling 3-4 weeks',
                                                   'PROM flexion',
                                                   'PROM ER ~30°',
                                                   'Pendulums',
                                                   'Scapular isometrics'],
                                           '4-6': ['AAROM', 'AROM', 'Pulleys', 'Isometrics', 'Scapular strengthening'],
                                           '6-12': ['Resisted ER/IR',
                                                    'Therabands',
                                                    'Scaption',
                                                    'IR stretch behind back'],
                                           '12-24': ['Advanced strengthening',
                                                     'Functional activities',
                                                     'Golf/gardening progression']}},
 'Reverse Total Shoulder Arthroplasty': {'body_region': 'Shoulder',
                                         'type': 'Arthroplasty',
                                         'frequency': '2-3x/week',
                                         'duration': '16-24 weeks',
                                         'outcome_measures': ['QuickDASH', 'SPADI'],
                                         'red_flags': ['Dislocation signs', 'Infection', 'Sudden loss of function'],
                                         'precautions': ['Avoid extension beyond neutral',
                                                         'Avoid adduction+extension+IR',
                                                         'No reaching behind back early'],
                                         'weeks': {'0-6': ['Sling 4-6 weeks',
                                                           'PROM shoulder',
                                                           'Pendulums',
                                                           'Scapular retractions',
                                                           'Elbow ROM',
                                                           'No shoulder AROM'],
                                                   '7-12': ['AAROM/AROM',
                                                            'Deltoid isometrics',
                                                            'Scapular strengthening',
                                                            'No lifting >1-2 lb'],
                                                   '12-16': ['Wall slides',
                                                             'Single-arm flexion',
                                                             'Progressive deltoid strengthening'],
                                                   '16-24': ['Advanced strengthening',
                                                             'Functional reaching',
                                                             'Recreational activities']}},
 'Proximal Humerus ORIF': {'body_region': 'Shoulder',
                           'type': 'Fracture ORIF',
                           'frequency': '2-3x/week',
                           'duration': '12-16+ weeks',
                           'outcome_measures': ['QuickDASH', 'SPADI'],
                           'red_flags': ['Infection', 'Hardware pain', 'Sudden ROM loss'],
                           'precautions': ['ER limited 40° early', 'ABD limited 90° early', 'No lifting >1 lb early'],
                           'weeks': {'1-4': ['Sling 3 weeks',
                                             'PROM shoulder',
                                             'Pendulums',
                                             'ER to 40°',
                                             'ABD to 90°',
                                             'Scapular retractions'],
                                     '4-8': ['AAROM/AROM',
                                             'Table/wall slides',
                                             'Pulleys',
                                             'Shoulder isometrics',
                                             'Biceps/triceps'],
                                     '8-12': ['PNF diagonals',
                                              'Prone I/Y/T',
                                              'Rows',
                                              'Resisted ER/IR',
                                              'Doorway stretch'],
                                     '12+': ['Push-up progression',
                                             'Rhythmic stabilization',
                                             'Scaption',
                                             'Plyometrics']}},
 'Adhesive Capsulitis': {'body_region': 'Shoulder',
                         'type': 'Non-operative',
                         'frequency': '1-2x/week',
                         'duration': '8-12+ weeks',
                         'outcome_measures': ['QuickDASH', 'SPADI'],
                         'red_flags': ['Unexplained systemic symptoms', 'Traumatic ROM loss'],
                         'precautions': ['Avoid aggressive stretching during high irritability/freezing phase'],
                         'weeks': {'Freezing': ['Pain control',
                                                'Pendulums',
                                                'Table slides',
                                                'Supine neutral ER',
                                                'Avoid aggressive stretching'],
                                   'Frozen': ['Supine flexion',
                                              'Wall slides',
                                              'IR behind back',
                                              'Joint mobilization',
                                              'Daily stretching'],
                                   'Thawing': ['Standing ER stretch',
                                               'Corner ER stretch',
                                               'Horizontal adduction',
                                               'Theraband strengthening']}},
 'AC Joint Repair/Reconstruction': {'body_region': 'Shoulder',
                                    'type': 'Ligament Reconstruction',
                                    'frequency': '2-3x/week',
                                    'duration': '12-24 weeks',
                                    'outcome_measures': ['QuickDASH', 'SPADI'],
                                    'red_flags': ['Instability', 'Infection', 'Hardware issues'],
                                    'precautions': ['No cross-body adduction early',
                                                    'No resisted forward flexion early'],
                                    'weeks': {'0-4': ['Sling',
                                                      'Flexion to 90°',
                                                      'ER/IR at 45° ABD',
                                                      'No cross-body adduction',
                                                      'Pendulums',
                                                      'Isometrics'],
                                              '4-6': ['Flexion to 120°',
                                                      'Advance isometrics',
                                                      'Scapular stabilization'],
                                              '6-12': ['Full AROM',
                                                       'Therabands',
                                                       'Light weights',
                                                       'RTC/periscapular strengthening'],
                                              '12-24': ['Functional strengthening',
                                                        'Push-ups',
                                                        'Pull-ups ~16 weeks',
                                                        'Sport-specific training']}},
 'Femoroacetabular Impingement (FAI)': {'body_region': 'Hip',
                                        'type': 'Hip Arthroscopy',
                                        'frequency': '2-3x/week',
                                        'duration': '16-24+ weeks',
                                        'outcome_measures': ['HOS', 'LEFS'],
                                        'red_flags': ['Fever', 'Drainage', 'Calf pain', 'Uncontrolled pain'],
                                        'precautions': ['20 lb foot-flat WB initially',
                                                        'No active hip flexion x21 days',
                                                        'No SLR early',
                                                        'Avoid pinching'],
                                        'weeks': {'0-2': ['20 lb WB',
                                                          'Crutches',
                                                          'Flexion 0-90°',
                                                          'No active hip flexion',
                                                          'Quad/glute sets',
                                                          'Bike no resistance'],
                                                  '3-5': ['Progress WBAT',
                                                          'Quadruped rocking',
                                                          'Bridges',
                                                          'Clamshells',
                                                          'Standing hip ABD',
                                                          'Counter plank'],
                                                  '6-11': ['Side planks',
                                                           'Squats to 90°',
                                                           'RDL progression',
                                                           'Band walks',
                                                           'Pallof press',
                                                           'Elliptical'],
                                                  '12-16': ['Advanced strengthening',
                                                            'Balance',
                                                            'Agility',
                                                            'Plyometrics as appropriate'],
                                                  '16+': ['Return-to-run', 'Sport-specific drills', 'Power training']}},
 'Greater Trochanteric Pain Syndrome': {'body_region': 'Hip',
                                        'type': 'Non-operative',
                                        'frequency': '1-2x/week',
                                        'duration': '6-12 weeks',
                                        'outcome_measures': ['LEFS', 'NPRS'],
                                        'red_flags': ['Suspected fracture', 'Lumbar red flags', 'Infection signs'],
                                        'precautions': ['Avoid lying on painful side',
                                                        'Avoid compressive hip adduction positions early'],
                                        'weeks': {'0-2': ['Activity modification',
                                                          'Hip flexor/hamstring stretch',
                                                          'Glute sets',
                                                          'TA activation',
                                                          'Iso hip ABD'],
                                                  '2-6': ['Clamshells',
                                                          'Side-lying hip ABD',
                                                          'Bridges',
                                                          'Lateral band walks',
                                                          'Hip hikes',
                                                          'SLS'],
                                                  '6-12': ['Step-ups/downs',
                                                           'Lunges',
                                                           'Squats',
                                                           'Single-leg RDL',
                                                           'Y-balance'],
                                                  '12+': ['Running progression',
                                                          'Agility',
                                                          'Power training',
                                                          'Maintenance glute strengthening']}},
 'Hip Osteoarthritis (Non-Operative)': {'body_region': 'Hip',
                                        'type': 'Non-operative',
                                        'frequency': '1-2x/week',
                                        'duration': '6-12 weeks',
                                        'outcome_measures': ['LEFS', 'HOOS'],
                                        'red_flags': ['Severe night pain', 'Unexplained weight loss', 'Fracture signs'],
                                        'precautions': ['Avoid painful overload', 'Avoid faulty movement patterns'],
                                        'weeks': {'0-4': ['Glute sets',
                                                          'Glute med isometrics',
                                                          'Core isometrics',
                                                          'Leg press 0-90°',
                                                          'Bridges',
                                                          'Mini squats',
                                                          'Bike'],
                                                  '4-8': ['Planks',
                                                          'Dead bugs',
                                                          'Pallof press',
                                                          'SL bridge',
                                                          'Lateral band walks',
                                                          'Step-downs',
                                                          'Elliptical'],
                                                  '8-12+': ['Single-leg RDL',
                                                            'Loaded strengthening',
                                                            'Lift/chop',
                                                            'Walking/hiking progression']}},
 'Lateral Ankle Sprain': {'body_region': 'Foot/Ankle',
                          'type': 'Non-operative',
                          'frequency': '1-2x/week',
                          'duration': '2-8+ weeks',
                          'outcome_measures': ['FAAM', 'LEFS'],
                          'red_flags': ['Unable to bear weight', 'Fracture signs', 'Severe swelling'],
                          'precautions': ['Protect ligaments early', 'Brace/boot for severe sprains'],
                          'weeks': {'0-1': ['PRICE',
                                            'WBAT',
                                            'Crutches PRN',
                                            'Ice',
                                            'Compression',
                                            'Elevation',
                                            'Grade I-II talocrural mobs'],
                                    '1-2': ['DF/PF ROM', 'Progress INV/EV', 'Gastroc/soleus stretch', 'Normalize gait'],
                                    '2-6': ['Theraband 4-way', 'SLS', 'BOSU/BAPS', 'Star excursion', 'Bike/swim'],
                                    '6+': ['Agility ladder',
                                           'Hopping',
                                           'Box jumps',
                                           'Cutting',
                                           'Return-to-sport testing']}},
 'Plantar Fasciitis': {'body_region': 'Foot/Ankle',
                       'type': 'Non-operative',
                       'frequency': '1-2x/week',
                       'duration': '4-12+ weeks',
                       'outcome_measures': ['FAAM', 'LEFS'],
                       'red_flags': ['Numbness/neuropathy', 'Stress fracture signs', 'Systemic inflammatory signs'],
                       'precautions': ['Avoid barefoot walking', 'Modify running/walking load'],
                       'weeks': {'0-2': ['Ice',
                                         'Gastroc stretch',
                                         'Soleus stretch',
                                         'Plantar fascia stretch',
                                         'Arch support',
                                         'Heel cup'],
                                 '2-6': ['Towel scrunches',
                                         'Marble pickups',
                                         'Short foot',
                                         'Toe yoga',
                                         'SLS',
                                         'Orthotics PRN'],
                                 '6-12': ['Heel raises',
                                          'Eccentric heel raises',
                                          'SL heel raises',
                                          'Resisted ankle strengthening'],
                                 '12+': ['Running/hiking progression',
                                         'Advanced calf strengthening',
                                         'Plyometrics as tolerated']}},
 'Brostrom Reconstruction': {'body_region': 'Foot/Ankle',
                             'type': 'Ligament Reconstruction',
                             'frequency': '2-3x/week',
                             'duration': '20-24+ weeks',
                             'outcome_measures': ['FAAM', 'CAIT'],
                             'red_flags': ['Infection', 'DVT signs', 'Instability'],
                             'precautions': ['NWB first 2 weeks', 'Avoid inversion early', 'Protect ATFL/CFL repair'],
                             'weeks': {'0-2': ['NWB crutches',
                                               'No inversion/PF ROM',
                                               'Quad sets',
                                               'SLR',
                                               'Hip ABD',
                                               'Hamstring curls'],
                                       '3-6': ['WBAT in boot',
                                               'DF/PF/EV ROM',
                                               'Avoid inversion',
                                               'Isometrics except inversion',
                                               'Clamshells'],
                                       '7-8': ['Shoe with brace',
                                               '4-way Theraband',
                                               'Calf raises',
                                               'Leg press',
                                               'SLS',
                                               'Bike'],
                                       '9-12': ['SL calf raises',
                                                'Squats',
                                                'Deadlifts',
                                                'Y-balance',
                                                'Ball toss balance'],
                                       '12-16': ['Elliptical', 'Lateral lunges', 'SL press', 'Hop progression'],
                                       '20-24': ['Running', 'Agility', 'Plyometrics', 'Return to sport']}},
 'Ankle ORIF': {'body_region': 'Foot/Ankle',
                'type': 'Fracture ORIF',
                'frequency': '2-3x/week',
                'duration': '16-24+ weeks',
                'outcome_measures': ['FAAM', 'LEFS'],
                'red_flags': ['DVT signs', 'Infection', 'Hardware issues'],
                'precautions': ['WB per surgeon',
                                'No joint mobs over fracture site early',
                                'No IASTM over fracture until cleared'],
                'weeks': {'0-6': ['WB per surgeon',
                                  'Boot/cast',
                                  'Ankle pumps/circles',
                                  'DF/PF ROM',
                                  'Toe stretch',
                                  'Hip/core strengthening'],
                          '7-12': ['Progress FWB',
                                   'Wean boot',
                                   'Theraband 4-way',
                                   'Standing calf raises',
                                   'Leg press',
                                   'SLS',
                                   'Bike'],
                          '13-16': ['Unilateral heel raises',
                                    'Hip hikes',
                                    'Lunges',
                                    'Squats',
                                    'Step-ups/downs',
                                    'BOSU'],
                          '17-20': ['Elliptical', 'Stair climber', 'Rebounding heel raises', 'Bilateral/SL hopping'],
                          '20+': ['Running', 'Agility ladder', 'Box jumps', 'Bounding', 'Return-to-sport testing']}},
 'Achilles Tendinopathy': {'body_region': 'Foot/Ankle',
                           'type': 'Non-operative',
                           'frequency': '1-2x/week',
                           'duration': '8-12+ weeks',
                           'outcome_measures': ['FAAM', 'VISA-A'],
                           'red_flags': ['Rupture signs', 'Sudden pop', 'Unable to perform heel raise'],
                           'precautions': ['Modify running/jumping load',
                                           'Insertional cases avoid aggressive dorsiflexion below neutral'],
                           'weeks': {'0-2': ['Activity modification', 'Ice', 'Theraband PF/DF/INV/EV', 'Heel lift PRN'],
                                     '2-4': ['Gastroc stretch', 'Soleus stretch', 'DF stretch', 'Continue Theraband'],
                                     '4-8': ['Double-leg heel raises',
                                             'SLS',
                                             'Balance progression',
                                             'Walking progression'],
                                     '8-12': ['Single-leg heel raises', 'Eccentric heel raises', 'Advanced balance'],
                                     '12+': ['Running progression', 'Jump progression', 'Sport-specific drills']}},
 'Achilles Tendon Reconstruction': {'body_region': 'Foot & Ankle',
                                    'type': 'Tendon Reconstruction',
                                    'frequency': '2-3x/week',
                                    'duration': '24+ weeks',
                                    'outcome_measures': ['FAAM', 'LEFS'],
                                    'red_flags': ['Excessive swelling',
                                                  'Wound complications',
                                                  'Re-rupture signs',
                                                  'DVT signs'],
                                    'precautions': ['No weight bearing first 2-4 weeks',
                                                    'Boot with heel lift',
                                                    'Avoid dorsiflexion past neutral early',
                                                    'Protect FHL transfer'],
                                    'weeks': {'0-2': ['NWB with crutches',
                                                      'Cast with ankle plantarflexed 20°',
                                                      'Protect reconstruction'],
                                              '2-4': ['Walking boot with heel lift',
                                                      'NWB',
                                                      'Active PF/DF to neutral',
                                                      'Inversion/eversion below neutral',
                                                      'EMS calf',
                                                      'Seated heel raises',
                                                      'Hip and knee strengthening',
                                                      'One-leg bike'],
                                              '4-6': ['Progressive WB in boot',
                                                      'ROM progression',
                                                      'Lying calf raises',
                                                      'No ankle past neutral'],
                                              '6-8': ['100% WB',
                                                      'Theraband strengthening',
                                                      'Gait retraining',
                                                      'Bike',
                                                      'Hydrotherapy'],
                                              '8-12': ['Wean boot',
                                                       'Double-leg heel raises',
                                                       'Single-leg heel raise progression',
                                                       'Wobble board',
                                                       'Elliptical',
                                                       'Treadmill walking'],
                                              '12-16': ['Advanced strengthening',
                                                        'Advanced proprioception',
                                                        'Functional training',
                                                        'Power and endurance'],
                                              '16-24': ['Dynamic weight-bearing',
                                                        'Plyometrics',
                                                        'Sport-specific retraining',
                                                        'Running progression'],
                                              '24+': ['Return to sport']}},
 'Posterior Tibial Tendon Dysfunction (PTTD)': {'body_region': 'Foot/Ankle',
                                                'type': 'Non-operative',
                                                'frequency': '1-2x/week',
                                                'duration': '8-12+ weeks',
                                                'outcome_measures': ['FAAM', 'LEFS'],
                                                'red_flags': ['Rapid arch collapse',
                                                              'Unable SL heel raise',
                                                              'Severe swelling'],
                                                'precautions': ['Avoid painful overloading',
                                                                'Use orthotic/bracing as needed'],
                                                'weeks': {'0-2': ['Sole-to-sole exercise',
                                                                  '25 reps x 4-12 sets/day',
                                                                  'Activity modification',
                                                                  'Ice',
                                                                  'Swimming/cycling'],
                                                          '1-4': ['Theraband inversion/eversion',
                                                                  '200 reps',
                                                                  'Controlled eccentric return'],
                                                          '4-8': ['Gastroc stretch',
                                                                  'DL to SL heel raises',
                                                                  'BAPS board',
                                                                  'Toe walking',
                                                                  'Increase band resistance'],
                                                          '8-12': ['Goal 50 SL heel raises',
                                                                   '150 ft toe walk',
                                                                   'Functional strengthening',
                                                                   'Return to activity']}},
 'Cervical Radiculopathy': {'body_region': 'Cervical',
                            'type': 'Non-operative',
                            'frequency': '1-2x/week',
                            'duration': '6-12 weeks',
                            'outcome_measures': ['NDI', 'NPRS'],
                            'red_flags': ['Progressive weakness', 'Myelopathy signs', 'Bowel/bladder changes'],
                            'precautions': ['Avoid symptom peripheralization', 'Modify prolonged sitting/lifting'],
                            'weeks': {'1-2': ['Chin tucks',
                                              'Cervical retractions',
                                              'Scapular squeezes',
                                              'Isometrics',
                                              'Gentle ROM',
                                              'Posture education'],
                                      '3-6': ['Progress ROM',
                                              'Upper trap stretch',
                                              'Levator stretch',
                                              'Resisted isometrics',
                                              'Band rows'],
                                      '6-12': ['Chin tucks with resistance',
                                               'Planks',
                                               'Wall angels',
                                               'Scapular stabilization',
                                               'Functional lifting'],
                                      '12+': ['Work/sport-specific training',
                                              'Maintenance strengthening',
                                              'Independent HEP']}},
 'Cervicogenic Headache': {'body_region': 'Cervical',
                           'type': 'Non-operative',
                           'frequency': '1-2x/week',
                           'duration': '6-8+ weeks',
                           'outcome_measures': ['NDI', 'Headache frequency', 'NPRS'],
                           'red_flags': ['Worst headache of life', 'Neurologic signs', 'Dizziness red flags'],
                           'precautions': ['Avoid symptom provocation', 'Screen for vascular/neurologic red flags'],
                           'weeks': {'0-2': ['Chin tucks',
                                             'Cervical retractions',
                                             'Scapular retractions',
                                             'Suboccipital release',
                                             'Ergonomic education'],
                                     '2-6': ['Deep neck flexor training',
                                             'Retraction with lift',
                                             'Rows',
                                             'Wall angels',
                                             'UT/levator stretch'],
                                     '6-8': ['4-way cervical resistance',
                                             'Dynamic stabilization',
                                             'Prone Y/T/W',
                                             'Cervical proprioception'],
                                     '8+': ['Maintenance neck/scap strengthening',
                                            'Work tolerance',
                                            'Independent HEP']}},
 'Knee Osteoarthritis (Non-Operative)': {'body_region': 'Knee',
                                         'type': 'Non-operative',
                                         'frequency': '1-2x/week',
                                         'duration': '6-12 weeks',
                                         'outcome_measures': ['LEFS', 'KOOS', 'TUG'],
                                         'red_flags': ['Hot swollen joint', 'Locking', 'DVT signs'],
                                         'precautions': ['No running/impact initially',
                                                         'Avoid excessive joint compression/shear'],
                                         'weeks': {'0-4': ['Cryotherapy',
                                                           'Quad sets',
                                                           'SLR',
                                                           'Hip ABD/ADD',
                                                           'Quarter squats',
                                                           'Bike high seat',
                                                           'HS/gastroc/quad stretch'],
                                                   '4-8': ['Wall squats',
                                                           'Front lunges',
                                                           'Lateral step-ups',
                                                           'Bike progression',
                                                           'Pool program',
                                                           'Walking progression'],
                                                   '8+': ['Half squats',
                                                          'Lunges',
                                                          'Bike',
                                                          'Walking program',
                                                          'Exercise 3-4x/week']}},
 'Patellofemoral Pain Syndrome': {'body_region': 'Knee',
                                  'type': 'Non-operative',
                                  'frequency': '1-2x/week',
                                  'duration': '4-8 weeks',
                                  'outcome_measures': ['LEFS', 'KOOS'],
                                  'red_flags': ['Locking', 'Significant effusion', 'Instability'],
                                  'precautions': ['Avoid painful loading', 'Modify running/jumping/stairs'],
                                  'weeks': {'0-2': ['Quad isometrics',
                                                    'SLR',
                                                    'Bridges',
                                                    'Clamshells',
                                                    'Side-lying hip ABD',
                                                    'Core',
                                                    'Bike'],
                                            '2-4': ['Monster walks',
                                                    'Sumo walks',
                                                    '4-way hip',
                                                    'SLS',
                                                    'Clock taps',
                                                    'Movement correction'],
                                            '4-6': ['Partial squats',
                                                    'Wall slides',
                                                    'Lunges',
                                                    'Step-ups',
                                                    'Step-downs',
                                                    'Eccentric strengthening'],
                                            '6+': ['Running progression',
                                                   'Sport-specific drills',
                                                   'Landing mechanics']}},
 'Quadriceps Tendon Repair': {'body_region': 'Knee',
                              'type': 'Tendon Repair',
                              'frequency': '2-3x/week',
                              'duration': '16-20+ weeks',
                              'outcome_measures': ['LEFS', 'KOOS'],
                              'red_flags': ['Extensor lag worsening', 'Infection', 'DVT signs'],
                              'precautions': ['Brace locked early', 'Protect repair', 'ROM limits early'],
                              'weeks': {'0-2': ['TDWB',
                                                'Brace locked extension',
                                                'ROM 0-45° flexion',
                                                'Quad sets',
                                                'Hamstring isometrics',
                                                'NMES'],
                                        '2-6': ['WBAT',
                                                'Brace locked WB',
                                                'Open to 90° sitting',
                                                'ROM 0-90°',
                                                'Quad activation'],
                                        '6-8': ['FWB',
                                                'Wean crutches',
                                                'Brace off if no lag',
                                                'SLR',
                                                'Closed-chain',
                                                'Bike'],
                                        '8-10': ['Advanced closed-chain', 'Balance', 'Full AROM/PROM'],
                                        '10-16': ['Open-chain strengthening', 'Swimming', 'Treadmill', 'Elliptical'],
                                        '16-20': ['Running progression', 'Sport-specific drills']}},
 'Patellar Tendon Repair': {'body_region': 'Knee',
                            'type': 'Tendon Repair',
                            'frequency': '2-3x/week',
                            'duration': '16-20+ weeks',
                            'outcome_measures': ['LEFS', 'KOOS'],
                            'red_flags': ['Extensor lag worsening', 'Infection', 'DVT signs'],
                            'precautions': ['Brace locked early', 'Protect repair', 'ROM limits early'],
                            'weeks': {'0-2': ['TDWB',
                                              'Brace locked extension',
                                              'ROM 0-45° flexion',
                                              'Quad sets',
                                              'Hamstring isometrics',
                                              'NMES'],
                                      '2-6': ['WBAT',
                                              'Brace locked WB',
                                              'Open to 90° sitting',
                                              'ROM 0-90°',
                                              'Quad activation'],
                                      '6-8': ['FWB',
                                              'Wean crutches',
                                              'Brace off if no lag',
                                              'SLR',
                                              'Closed-chain',
                                              'Bike'],
                                      '8-10': ['Advanced closed-chain', 'Balance', 'Full AROM/PROM'],
                                      '10-16': ['Open-chain strengthening', 'Swimming', 'Treadmill', 'Elliptical'],
                                      '16-20': ['Running progression', 'Sport-specific drills']}},
 'PCL Reconstruction': {'body_region': 'Knee',
                        'type': 'Ligament Reconstruction',
                        'frequency': '2-3x/week',
                        'duration': '24-28+ weeks',
                        'outcome_measures': ['LEFS', 'IKDC'],
                        'red_flags': ['Instability', 'DVT signs', 'Infection'],
                        'precautions': ['No hamstring activation until 6-8 weeks',
                                        'Avoid posterior tibial translation',
                                        'Limit flexion early'],
                        'weeks': {'0-2': ['PWB crutches',
                                          'Brace locked',
                                          'NMES',
                                          'Quad sets',
                                          'SLR',
                                          'Patellar mobs',
                                          'Cryotherapy'],
                                  '2-4': ['Flexion to 60° week 2',
                                          'Flexion to 90° week 4',
                                          'SAQ 30-0°',
                                          'Bike ROM',
                                          'PWB'],
                                  '4-12': ['Closed-chain strengthening',
                                           'Step-ups',
                                           'Mini squats',
                                           'Hip strengthening',
                                           'Balance',
                                           'Elliptical'],
                                  '12-15': ['Hamstring exercises', 'Functional strengthening', 'Advanced balance'],
                                  '16-24': ['Running progression', 'Hamstring curls', 'Agility'],
                                  '24-28': ['Return to sport', 'Sport-specific training']}},
 'ACL Reconstruction - Patellar Tendon Autograft': {'body_region': 'Knee',
                                                    'type': 'Ligament Reconstruction',
                                                    'frequency': '2-3x/week',
                                                    'duration': 'Varies by protocol',
                                                    'outcome_measures': ['LEFS'],
                                                    'red_flags': ['Follow surgeon/MD restrictions',
                                                                  'Worsening symptoms',
                                                                  'Infection/DVT signs if post-op'],
                                                    'precautions': ['Use uploaded surgeon protocol specifics'],
                                                    'weeks': {'See protocol': ['Protocol entry placeholder - replace '
                                                                               'with detailed uploaded protocol text '
                                                                               'as needed']}},
 'ACL Reconstruction - Hamstring Autograft': {'body_region': 'Knee',
                                              'type': 'Ligament Reconstruction',
                                              'frequency': '2-3x/week',
                                              'duration': 'Varies by protocol',
                                              'outcome_measures': ['LEFS'],
                                              'red_flags': ['Follow surgeon/MD restrictions',
                                                            'Worsening symptoms',
                                                            'Infection/DVT signs if post-op'],
                                              'precautions': ['Use uploaded surgeon protocol specifics'],
                                              'weeks': {'See protocol': ['Protocol entry placeholder - replace with '
                                                                         'detailed uploaded protocol text as needed']}},
 'ACL Reconstruction - Allograft': {'body_region': 'Knee',
                                    'type': 'Ligament Reconstruction',
                                    'frequency': '2-3x/week',
                                    'duration': 'Varies by protocol',
                                    'outcome_measures': ['LEFS'],
                                    'red_flags': ['Follow surgeon/MD restrictions',
                                                  'Worsening symptoms',
                                                  'Infection/DVT signs if post-op'],
                                    'precautions': ['Use uploaded surgeon protocol specifics'],
                                    'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed '
                                                               'uploaded protocol text as needed']}},
 'MPFL Reconstruction': {'body_region': 'Knee',
                         'type': 'Ligament Reconstruction',
                         'frequency': '2-3x/week',
                         'duration': 'Varies by protocol',
                         'outcome_measures': ['LEFS'],
                         'red_flags': ['Follow surgeon/MD restrictions',
                                       'Worsening symptoms',
                                       'Infection/DVT signs if post-op'],
                         'precautions': ['Use uploaded surgeon protocol specifics'],
                         'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded '
                                                    'protocol text as needed']}},
 'Rotator Cuff Repair - Small/Medium': {'body_region': 'Shoulder',
                                        'type': 'Tendon Repair',
                                        'frequency': '2-3x/week',
                                        'duration': 'Varies by protocol',
                                        'outcome_measures': ['QuickDASH'],
                                        'red_flags': ['Follow surgeon/MD restrictions',
                                                      'Worsening symptoms',
                                                      'Infection/DVT signs if post-op'],
                                        'precautions': ['Use uploaded surgeon protocol specifics'],
                                        'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed '
                                                                   'uploaded protocol text as needed']}},
 'Rotator Cuff Repair - Large/Massive': {'body_region': 'Shoulder',
                                         'type': 'Tendon Repair',
                                         'frequency': '2-3x/week',
                                         'duration': 'Varies by protocol',
                                         'outcome_measures': ['QuickDASH'],
                                         'red_flags': ['Follow surgeon/MD restrictions',
                                                       'Worsening symptoms',
                                                       'Infection/DVT signs if post-op'],
                                         'precautions': ['Use uploaded surgeon protocol specifics'],
                                         'weeks': {'See protocol': ['Protocol entry placeholder - replace with '
                                                                    'detailed uploaded protocol text as needed']}},
 'Anterior Bankart Repair': {'body_region': 'Shoulder',
                             'type': 'Labral Repair',
                             'frequency': '2-3x/week',
                             'duration': 'Varies by protocol',
                             'outcome_measures': ['QuickDASH'],
                             'red_flags': ['Follow surgeon/MD restrictions',
                                           'Worsening symptoms',
                                           'Infection/DVT signs if post-op'],
                             'precautions': ['Use uploaded surgeon protocol specifics'],
                             'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded '
                                                        'protocol text as needed']}},
 'Posterior Bankart Repair': {'body_region': 'Shoulder',
                              'type': 'Labral Repair',
                              'frequency': '2-3x/week',
                              'duration': 'Varies by protocol',
                              'outcome_measures': ['QuickDASH'],
                              'red_flags': ['Follow surgeon/MD restrictions',
                                            'Worsening symptoms',
                                            'Infection/DVT signs if post-op'],
                              'precautions': ['Use uploaded surgeon protocol specifics'],
                              'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded '
                                                         'protocol text as needed']}},
 'Lower Trapezius Transfer': {'body_region': 'Shoulder',
                              'type': 'Tendon Transfer',
                              'frequency': '2-3x/week',
                              'duration': 'Varies by protocol',
                              'outcome_measures': ['QuickDASH'],
                              'red_flags': ['Follow surgeon/MD restrictions',
                                            'Worsening symptoms',
                                            'Infection/DVT signs if post-op'],
                              'precautions': ['Use uploaded surgeon protocol specifics'],
                              'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded '
                                                         'protocol text as needed']}},
 'Distal Biceps Repair': {'body_region': 'Elbow',
                          'type': 'Tendon Repair',
                          'frequency': '2-3x/week',
                          'duration': 'Varies by protocol',
                          'outcome_measures': ['QuickDASH'],
                          'red_flags': ['Follow surgeon/MD restrictions',
                                        'Worsening symptoms',
                                        'Infection/DVT signs if post-op'],
                          'precautions': ['Use uploaded surgeon protocol specifics'],
                          'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded '
                                                     'protocol text as needed']}},
 'Lateral Epicondylitis': {'body_region': 'Elbow',
                           'type': 'Non-operative',
                           'frequency': '2-3x/week',
                           'duration': 'Varies by protocol',
                           'outcome_measures': ['QuickDASH'],
                           'red_flags': ['Follow surgeon/MD restrictions',
                                         'Worsening symptoms',
                                         'Infection/DVT signs if post-op'],
                           'precautions': ['Use uploaded surgeon protocol specifics'],
                           'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded '
                                                      'protocol text as needed']}},
 'THA Anterior': {'body_region': 'Hip',
                  'type': 'Arthroplasty',
                  'frequency': '2-3x/week',
                  'duration': 'Varies by protocol',
                  'outcome_measures': ['LEFS'],
                  'red_flags': ['Follow surgeon/MD restrictions',
                                'Worsening symptoms',
                                'Infection/DVT signs if post-op'],
                  'precautions': ['Use uploaded surgeon protocol specifics'],
                  'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded protocol '
                                             'text as needed']}},
 'THA Posterior': {'body_region': 'Hip',
                   'type': 'Arthroplasty',
                   'frequency': '2-3x/week',
                   'duration': 'Varies by protocol',
                   'outcome_measures': ['LEFS'],
                   'red_flags': ['Follow surgeon/MD restrictions',
                                 'Worsening symptoms',
                                 'Infection/DVT signs if post-op'],
                   'precautions': ['Use uploaded surgeon protocol specifics'],
                   'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded protocol '
                                              'text as needed']}},
 'Lumbar Fusion': {'body_region': 'Lumbar',
                   'type': 'Spine Post-op',
                   'frequency': '2-3x/week',
                   'duration': 'Varies by protocol',
                   'outcome_measures': ['ODI'],
                   'red_flags': ['Follow surgeon/MD restrictions',
                                 'Worsening symptoms',
                                 'Infection/DVT signs if post-op'],
                   'precautions': ['Use uploaded surgeon protocol specifics'],
                   'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded protocol '
                                              'text as needed']}},
 'Lumbar Laminectomy': {'body_region': 'Lumbar',
                        'type': 'Spine Post-op',
                        'frequency': '2-3x/week',
                        'duration': 'Varies by protocol',
                        'outcome_measures': ['ODI'],
                        'red_flags': ['Follow surgeon/MD restrictions',
                                      'Worsening symptoms',
                                      'Infection/DVT signs if post-op'],
                        'precautions': ['Use uploaded surgeon protocol specifics'],
                        'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded '
                                                   'protocol text as needed']}},
 'Lumbar Discectomy': {'body_region': 'Lumbar',
                       'type': 'Spine Post-op',
                       'frequency': '2-3x/week',
                       'duration': 'Varies by protocol',
                       'outcome_measures': ['ODI'],
                       'red_flags': ['Follow surgeon/MD restrictions',
                                     'Worsening symptoms',
                                     'Infection/DVT signs if post-op'],
                       'precautions': ['Use uploaded surgeon protocol specifics'],
                       'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded '
                                                  'protocol text as needed']}},
 'Lumbar Stenosis': {'body_region': 'Lumbar',
                     'type': 'Non-operative',
                     'frequency': '2-3x/week',
                     'duration': 'Varies by protocol',
                     'outcome_measures': ['ODI'],
                     'red_flags': ['Follow surgeon/MD restrictions',
                                   'Worsening symptoms',
                                   'Infection/DVT signs if post-op'],
                     'precautions': ['Use uploaded surgeon protocol specifics'],
                     'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded protocol '
                                                'text as needed']}},
 'Low Back Pain': {'body_region': 'Lumbar',
                   'type': 'Non-operative',
                   'frequency': '2-3x/week',
                   'duration': 'Varies by protocol',
                   'outcome_measures': ['ODI'],
                   'red_flags': ['Follow surgeon/MD restrictions',
                                 'Worsening symptoms',
                                 'Infection/DVT signs if post-op'],
                   'precautions': ['Use uploaded surgeon protocol specifics'],
                   'weeks': {'See protocol': ['Protocol entry placeholder - replace with detailed uploaded protocol '
                                              'text as needed']}}}
