# PT Documentation Assistant Master Database v2
# Full detailed content added for: MPFL Reconstruction, ACL Hamstring Autograft, Total Knee Replacement.
# Other 19 diagnoses remain indexed and can be expanded in later versions.

protocols = {
    "Neck": {"Cervical": {}},
    "Arm": {
        "Shoulder": {
            "Post-operative Bankart Repair": {"status": "indexed", "phases": {}},
            "Posterior Bankart Repair": {"status": "indexed", "phases": {}},
            "Rotator Cuff Repair - Large Tear": {"status": "indexed", "phases": {}},
            "Rotator Cuff Repair - Small/Medium Tear": {"status": "indexed", "phases": {}},
            "Lower Trapezius Tendon Transfer": {"status": "indexed", "phases": {}},
        },
        "Elbow": {
            "Distal Biceps Repair": {"status": "indexed", "phases": {}},
            "Lateral Epicondylitis (Tennis Elbow)": {"status": "indexed", "phases": {}},
        },
        "Wrist": {},
    },
    "Back": {
        "Upper": {},
        "Middle": {},
        "Lower": {
            "Lumbar Fusion": {"status": "indexed", "phases": {}},
            "Lumbar Discectomy": {"status": "indexed", "phases": {}},
            "Lumbar Laminectomy": {"status": "indexed", "phases": {}},
            "Lumbar Spinal Stenosis": {"status": "indexed", "phases": {}},
            "Lumbar Disc Herniation": {"status": "indexed", "phases": {}},
            "Spondylolisthesis": {"status": "indexed", "phases": {}},
        },
    },
    "Leg": {
        "Hip": {
            "Total Hip Arthroplasty - Posterior Approach": {"status": "indexed", "phases": {}},
            "Total Hip Arthroplasty - Anterior Approach": {"status": "indexed", "phases": {}},
        },
        "Knee": {
            "ACL Reconstruction - Patellar Tendon Autograft": {"status": "indexed", "phases": {}},
            "ACL Reconstruction - Hamstring Tendon Autograft": {
                "phases": {
                    "Phase I: 0-4 weeks": {
                        "goals": ["Protect graft and fixation", "Control inflammation and swelling", "Restore full extension", "Restore gait", "Protect hamstring donor site"],
                        "precautions": ["Avoid hyperextension greater than 10 degrees", "Flexion limited to 90 degrees", "Delay hamstring strengthening", "Protect graft fixation"],
                        "brace": ["Week 0-1: locked in extension", "Weeks 1-3: unlock to less than 90 degrees as quad control allows", "Weeks 3-4: wean from brace"],
                        "weight_bearing": ["Week 0-1: PWB with two crutches", "Weeks 1-4: progress to FWB with normalized gait"],
                        "rom_restrictions": ["Flexion limited to 90 degrees", "Full extension emphasized"],
                        "manual_therapy": ["Patellar mobilization", "Edema management", "Scar mobilization"],
                        "therapeutic_exercise": ["Heel slides", "Quad sets", "NMES if indicated", "Gastroc/Soleus stretching", "Gentle hamstring stretching at week 1", "SLR all planes", "Quadriceps isometrics", "Aquatic therapy after suture removal"],
                        "criteria_to_progress": ["Full extension", "90 degrees flexion", "Good quad set", "SLR without lag", "Minimal swelling", "Normal gait"],
                    },
                    "Phase II: 4-10 weeks": {
                        "goals": ["Restore normal gait", "Progress toward full ROM", "Increase LE strength", "Improve proprioception"],
                        "precautions": ["Avoid aggressive hamstring strengthening", "Protect graft during revascularization"],
                        "brace": ["Continue weaning if needed"],
                        "weight_bearing": ["Full"],
                        "rom_restrictions": ["Progress toward full ROM"],
                        "manual_therapy": ["Patellar mobility", "Soft tissue mobility"],
                        "therapeutic_exercise": ["Wall sits", "Step-ups", "Mini squats", "Leg press 90-30", "Progressive hip strengthening", "Progressive calf strengthening", "Hamstring strengthening begins around week 12", "Stairmaster", "Elliptical", "Stationary bike", "Single-leg balance", "Balance beam", "Mini-tramp balance"],
                        "criteria_to_progress": ["120 degrees flexion", "Minimal swelling", "Adequate strength for running"],
                    },
                    "Phase III: 10-16 weeks": {
                        "goals": ["Restore full ROM", "Improve strength and endurance", "Normalize running mechanics", "Prepare for sport"],
                        "precautions": ["Gradually increase hamstring resistance", "Avoid graft overload"],
                        "brace": ["None"],
                        "weight_bearing": ["Full"],
                        "rom_restrictions": ["Full ROM"],
                        "manual_therapy": ["As needed"],
                        "therapeutic_exercise": ["Open-chain knee extension 90-30", "Progressive hamstring strengthening", "Running progression at approximately 16 weeks", "Swimming", "Hip strengthening", "Quadriceps strengthening", "Hamstring strengthening", "Calf strengthening", "Bike", "Elliptical", "Advanced balance training"],
                        "criteria_to_progress": ["Full pain-free ROM", "70 percent strength of uninvolved leg", "Normal running gait", "No significant swelling"],
                    },
                    "Phase IV: 4-6 months": {
                        "goals": ["Initiate agility", "Restore power", "Return to sport preparation"],
                        "precautions": ["Monitor donor site symptoms"],
                        "brace": ["None"],
                        "weight_bearing": ["Full"],
                        "rom_restrictions": ["None"],
                        "manual_therapy": ["As needed"],
                        "therapeutic_exercise": ["Plyometrics", "Side shuffles", "Crossovers", "Figure-8 running", "Shuttle runs", "Single-leg jumping", "Double-leg jumping", "Cutting drills", "Acceleration drills", "Deceleration drills", "Sprint progression", "Agility ladder"],
                        "criteria_to_progress": ["85 percent hop testing", "85 percent quadriceps strength", "85 percent hamstring strength"],
                    },
                    "Phase V: 6+ months": {
                        "goals": ["Return to sport", "Maintain strength", "Maintain endurance"],
                        "precautions": ["Follow surgeon clearance"],
                        "brace": ["Functional brace only if prescribed"],
                        "weight_bearing": ["Full"],
                        "rom_restrictions": ["None"],
                        "manual_therapy": ["As needed"],
                        "therapeutic_exercise": ["Sport-specific drills", "Advanced agility", "Maintenance strengthening", "Return-to-sport progression"],
                        "criteria_to_progress": ["Physician clearance", "Functional testing passed"],
                    },
                }
            },
            "ACL Reconstruction - Allograft": {"status": "indexed", "phases": {}},
            "ACL Reconstruction - Accelerated": {"status": "indexed", "phases": {}},
            "ACL Reconstruction - Delayed": {"status": "indexed", "phases": {}},
            "MPFL Reconstruction": {
                "phases": {
                    "Phase I: Immediate Post-Op (0-2 weeks)": {
                        "goals": ["Protect surgical site", "Reduce swelling and pain", "Restore full extension", "Improve flexion to at least 90 degrees", "Re-establish quadriceps control", "Patient education"],
                        "precautions": ["Avoid resting with towel under knee", "Protect reconstruction", "Monitor swelling and effusion"],
                        "brace": ["Brace locked initially", "Unlock per surgeon protocol"],
                        "weight_bearing": ["PWB first week", "Progress to WBAT with crutches", "Discontinue crutches once gait normal and pain controlled"],
                        "rom_restrictions": ["Restore full extension", "Flexion goal 90+ degrees"],
                        "manual_therapy": ["Retrograde massage", "Edema management", "Compression", "Elevation"],
                        "therapeutic_exercise": ["Ankle pumps", "PROM", "Heel slides with towel", "Prone hangs", "Heel props", "Hamstring stretch", "Calf stretch", "Calf raises", "Quad sets", "NMES if indicated", "SLR progression"],
                        "criteria_to_progress": ["SLR without lag", "Full extension", "Minimal swelling"],
                    },
                    "Phase II: Intermediate (3-6 weeks)": {
                        "goals": ["Protect surgical site", "Restore full flexion", "Normalize gait", "Maintain full extension"],
                        "precautions": ["Avoid excessive patellofemoral stress"],
                        "brace": ["May unlock when SLR without lag", "Discontinue brace at 6 weeks when gait normalized"],
                        "weight_bearing": ["WBAT"],
                        "rom_restrictions": ["Restore full ROM"],
                        "manual_therapy": ["Patellar mobilization if stiffness present"],
                        "therapeutic_exercise": ["Stationary bike", "Ball squeezes", "SLR adduction", "Bridges with ball squeeze", "Wall slides", "Mini squats 0-60 degrees", "Single-leg balance"],
                        "criteria_to_progress": ["No swelling", "Flexion greater than 90 degrees", "Extension equal to contralateral side"],
                    },
                    "Phase III: Late Post-Op (7-12 weeks)": {
                        "goals": ["Maintain full ROM", "Progress strengthening", "Improve movement patterns", "Improve proprioception"],
                        "precautions": ["Avoid post-exercise pain or swelling"],
                        "brace": ["None"],
                        "weight_bearing": ["FWB without assistive device"],
                        "rom_restrictions": ["Full ROM"],
                        "manual_therapy": ["As needed"],
                        "therapeutic_exercise": ["Prone quad stretch", "Standing quad stretch", "Hip flexor stretch", "Elliptical", "Stair climber", "Pool jogging", "Flutter kick swimming", "Leg press", "Hamstring curls", "Hip abductor machine", "Hip adductor machine", "Hip extension machine", "Calf machine", "Lateral band walks", "Perturbation balance training"],
                        "criteria_to_progress": ["Normal gait", "ROM equal to contralateral side", "Quad/Hamstring/Glute index at least 70 percent"],
                    },
                    "Phase IV: Transitional (13-16 weeks)": {
                        "goals": ["Maintain full ROM", "Progress strengthening", "Improve landing mechanics", "Prepare for running"],
                        "precautions": ["Avoid pain-producing activities"],
                        "brace": ["None"],
                        "weight_bearing": ["Full"],
                        "rom_restrictions": ["None"],
                        "manual_therapy": ["As needed"],
                        "therapeutic_exercise": ["Advanced strengthening", "Single-leg balance", "Perturbation training", "Bilateral plyometrics", "Single-leg plyometrics"],
                        "criteria_to_progress": ["Quad/Hamstring/Glute index at least 80 percent", "Hop testing at least 80 percent", "Good landing mechanics", "Physician clearance"],
                    },
                    "Phase V: Early Return to Sport (3-5 months)": {
                        "goals": ["Initiate sport-specific training", "Improve strength and power", "Begin running progression"],
                        "precautions": ["Avoid graft donor site pain", "Monitor swelling"],
                        "brace": ["None"],
                        "weight_bearing": ["Full"],
                        "rom_restrictions": ["None"],
                        "manual_therapy": ["As needed"],
                        "therapeutic_exercise": ["Return-to-running program", "Strength progression", "Sport-specific drills", "Plyometric progression"],
                        "criteria_to_progress": ["KOOS Sports greater than 90", "IKDC greater than 93", "PRRS greater than 90", "Kujala greater than 90"],
                    },
                    "Phase VI: Unrestricted Return to Sport (6+ months)": {
                        "goals": ["Return to unrestricted sport", "Restore full performance", "Maintain strength and power"],
                        "precautions": ["Continue symptom monitoring"],
                        "brace": ["None"],
                        "weight_bearing": ["Full"],
                        "rom_restrictions": ["None"],
                        "manual_therapy": ["As needed"],
                        "therapeutic_exercise": ["Multi-plane plyometrics", "Agility progression", "Hard cutting drills", "Pivoting drills", "Full practice progression", "Return-to-play progression"],
                        "criteria_to_progress": ["Quad/Hamstring/Glute index at least 90 percent", "Hamstring/Quad ratio at least 70 percent", "Hop testing at least 90 percent", "KOOS Sports greater than 90", "IKDC greater than 93", "ACL-RSI acceptable", "Physician clearance"],
                    },
                }
            },
            "Total Knee Replacement": {
                "phases": {
                    "Phase I: 0-2 weeks": {
                        "goals": ["Control pain and swelling", "Restore knee extension", "Improve knee flexion", "Activate quadriceps", "Improve safe gait with assistive device"],
                        "precautions": ["Monitor incision", "Monitor excessive swelling", "Avoid placing pillow under knee for prolonged periods", "Watch for signs of DVT or infection"],
                        "brace": ["None unless prescribed"],
                        "weight_bearing": ["WBAT unless otherwise instructed"],
                        "rom_restrictions": ["Emphasize full knee extension", "Progress knee flexion as tolerated"],
                        "manual_therapy": ["Patellar mobilizations", "Scar mobility when incision healed", "Edema management", "PROM/AAROM knee flexion and extension"],
                        "therapeutic_exercise": ["Ankle pumps", "Quad sets", "Glute sets", "Heel slides", "Short arc quads", "SLR if no quad lag", "Seated knee flexion", "LAQ as tolerated", "Gait training", "Stair training as appropriate"],
                        "criteria_to_progress": ["Pain controlled", "Improved quad activation", "Improving knee ROM", "Safe ambulation with assistive device"],
                    },
                    "Phase II: 2-6 weeks": {
                        "goals": ["Improve ROM", "Normalize gait mechanics", "Increase quadriceps and hip strength", "Improve balance", "Improve functional mobility"],
                        "precautions": ["Avoid excessive post-treatment swelling", "Monitor pain response"],
                        "brace": ["None"],
                        "weight_bearing": ["WBAT", "Progress away from assistive device as safe"],
                        "rom_restrictions": ["Progress toward functional ROM"],
                        "manual_therapy": ["Patellar mobilizations", "Tibiofemoral mobilizations as appropriate", "Soft tissue mobilization", "Scar mobilization when healed"],
                        "therapeutic_exercise": ["Bike rocking", "Stationary bike", "Mini squats", "Step-ups", "Sit-to-stands", "Terminal knee extensions", "Standing hip strengthening", "Calf raises", "Hamstring curls", "Balance training", "Gait training"],
                        "criteria_to_progress": ["Improved gait quality", "Improved ROM", "Good tolerance to strengthening", "Reduced assistive device dependence"],
                    },
                    "Phase III: 6-12 weeks": {
                        "goals": ["Restore functional strength", "Improve endurance", "Improve stair negotiation", "Improve balance and community ambulation"],
                        "precautions": ["Progress strengthening gradually", "Monitor swelling after activity"],
                        "brace": ["None"],
                        "weight_bearing": ["Full"],
                        "rom_restrictions": ["Functional ROM expected"],
                        "manual_therapy": ["Manual therapy as needed for ROM limitations", "Soft tissue mobility as needed"],
                        "therapeutic_exercise": ["Leg press", "Step-downs", "Lateral stepping", "Resisted hip strengthening", "Progressive squats", "Single-leg balance", "Treadmill walking", "Bike", "Elliptical if tolerated", "Functional lifting mechanics"],
                        "criteria_to_progress": ["Independent gait or least restrictive device", "Improved stair function", "Improved functional strength", "Independent with HEP"],
                    },
                }
            },
        },
        "Ankle": {},
        "Foot": {},
    },
}
